apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2021-04-20T18:54:22Z
  labels:
    app: spring-test3
  name: spring-test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-test3
  strategy: {}
  template:
    metadata:
      creationTimestamp: 2021-04-20T18:54:22Z
      labels:
        app: spring-test3
    spec:
      containers:
      - name: spring-test3
        image: balavigneswaran/spring-test3:latest
        imagePullPolicy: Always
        resources: {}
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          periodSeconds: 120
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        volumeMounts:
          - mountPath: /workspace/config
            name: config-volume
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: spring-test3-global-config
                key: app.profiles.active
          # - name: SPRING_PROFILES_ACTIVE
          #   value: sit2
          # - name: JAVA_OPTIONS
          #   value: "-Dspring.profiles.active=${SPRING_PROFILE}"
          # - name: SPRING_PROFILE
          #   valueFrom:
          #     configMapKeyRef:
          #       name: spring-test3-global-config
          #       key: app.profiles.active
          - name: REGION_CD
            valueFrom:
              configMapKeyRef:
                name: spring-test3-config2
                key: region.cd
          - name: dialect
            valueFrom:
              configMapKeyRef:
                name: spring-test3-config2
                key: dialect
      volumes:
        - name: config-volume
          configMap:
            name: spring-test3-config-yaml
status: {}
