app:
  lives: "4000"
  enemies:
    cheat:
      level: ENC(bGhvDwjfNy06NT8k2b2btMdyh+jWmFD46TDBHYaN31U/vMsHXD/gAJEQxc7u3DRv)
  url:
    nameService: http://k8s-workshop-name-service
  hello:
    message: Hello SIT4 World!!!
    from-id: bala@sit4-xyz.com
