# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: spring-test-100
# data:
#   lives: "2500"
#   enemies.cheat.level: "noGoodRotten"

apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-test3-global-config
data:
  app.profiles.active: "sit4"
